[world]
name = "Provable Games"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_9"
world_address = "0x02ef591697f0fd9adc0ba9dbe0ca04dabad80cf95f08ba02e435d9cb6698a28a"
world_block = 2125240
max_block_range = 20000

[namespace]
default = "summit_relayer_6"

[writers]
"summit_relayer_6" = [
    "summit_relayer_6-summit_events",
]

[init_call_args]
"summit_relayer_6-summit_events" = [
    "0x04ec11a167e44d33d1bcd84b243f0d67b890e638f1760a3a29e5e357f362cd01", # summit_address
    "0x06504fb9d64cda31aaa7bfa425b410ae86ceb0ee154f2c85a61d145155eab1bc", # corpse_address
    "0x05169f2f5a20fdb8db9fa59a2014b35c31e6d8440d5f782a373cb1fe6cbc83e5" # skull_address
]