[world]
name = "Provable Games"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_9"
world_address = "0x02ef591697f0fd9adc0ba9dbe0ca04dabad80cf95f08ba02e435d9cb6698a28a"
world_block = 2125240
max_block_range = 20000

[namespace]
default = "summit_relayer_4"

[writers]
"summit_relayer_4" = [
    "summit_relayer_4-summit_events",
]

[init_call_args]
"summit_relayer_4-summit_events" = [
    "0x06726e35e526c2804e2e10080b326a1aa2579a274516971de40364ad492eef68", # summit_address
    "0x0773fc83a286a1a05131012d97c1e5970a930b5862641d750510959a7b8cb290", # corpse_address
    "0x056747f477c306759134c89ed8fb9c477ca96a229e6c0fd2b44731878f58e66d" # skull_address
]