[package]
cairo-version = "=2.10.1"
name = "summit"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.mainnet]