[world]
name = "Provable Games"
description = "DNC"
seed = "DNC"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_8"
world_address = "0x02ef591697f0fd9adc0ba9dbe0ca04dabad80cf95f08ba02e435d9cb6698a28a"
world_block = 2125240
max_block_range = 10000

[namespace]
default = "summit_0_0_9_preview"

[writers]
"summit_0_0_9_preview" = [
    "summit_0_0_9_preview-summit_systems",
]

[init_call_args]
"summit_0_0_9_preview-summit_systems" = [
    "1761057539",
    "0x3fc7ecd6d577daa1ee855a9fa13a914d01acda06715c9fc74f1ee1a5e346a01", # adventurer_systems
    "0x036017e69d21d6d8c13e266eabb73ef1f1d02722d86bdcabe5f168f8e549d3cd", # Denshokan
    "0x00a67ef20b61a9846e1c82b411175e6ab167ea9f8632bd6c2091823c3629ec42", # Dungeon
    "0x046da8955829adf2bda310099a0063451923f02e648cf25a1203aac6335cf0e4", # Beasts
    "0x74abc15c0ddef39bdf1ede2a643c07968d3ed5bacb0123db2d5b7154fbb35c7", # DM Beast Systems
    "0x042DD777885AD2C116be96d4D634abC90A26A790ffB5871E037Dd5Ae7d2Ec86B", # Survivor
    "0x075bbe6a4a4c744ad2da8da0cc7562623d4181418359d62909a02b4abf5be651", # Attack potion
    "0x003561384b4c4502f87fd728332f8cf4e604a1215185d9d997be33769ba32fc3", # Revive potion
    "0x07af033bf4a3f2cae7f871ca015c7021f97846217733d72665aaf6ad735d4359", # Extra life potion
    "0x047314b2b569360da4623035d2d81479a90a677beae8518e221960b07afb960f", # poison potion
    "0x02beaf101300efd433877bf358005d29c32e048e314529ac1fdbe4ac024c17cd", # kill token
    "0x0195685bd2bce86e4ebe4ea5ef44d9dc00c4e7c6e362d428abdb618b4739c25c", # corpse token
]