name: test-contracts

on:
  pull_request:
    paths-ignore:
      - "ui/**"
      - "**/manifest.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

  scarb-test:
    needs: [setup-environment]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract scarb version
        run: |
          SCARB_VERSION=$(grep '^scarb ' .tool-versions | awk '{print $2}')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"

      - name: Extract snforge version
        run: |
          SNFORGE_VERSION=$(grep '^snforge ' .tool-versions | awk '{print $2}')
          echo "SNFORGE_VERSION=$SNFORGE_VERSION" >> "$GITHUB_ENV"

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - name: Install Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: ${{ env.SNFORGE_VERSION }}

      - name: Run Scarb Build
        run: |
          cd contracts && scarb build

      - name: Run Tests
        run: |
          cd contracts && scarb test

  scarb-fmt:
    needs: [setup-environment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract scarb version
        run: |
          SCARB_VERSION=$(grep '^scarb ' .tool-versions | awk '{print $2}')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - run: cd contracts && scarb fmt --check
