name: test-contracts

on:
  pull_request:
    paths-ignore:
      - "ui/**"
      - "**/manifest.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scarb-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract scarb version
        run: |
          SCARB_VERSION=$(grep '^scarb ' .tool-versions | awk '{print $2}')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - run: cd contracts && scarb fmt --check

  scarb-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract versions
        run: |
          SCARB_VERSION=$(grep '^scarb ' .tool-versions | awk '{print $2}')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"
          SNFORGE_VERSION=$(grep '^starknet-foundry ' .tool-versions | awk '{print $2}')
          echo "SNFORGE_VERSION=$SNFORGE_VERSION" >> "$GITHUB_ENV"

      - name: Cache Scarb
        uses: actions/cache@v4
        with:
          path: ~/.cache/scarb
          key: scarb-${{ env.SCARB_VERSION }}-${{ hashFiles('contracts/Scarb.lock') }}

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - name: Install Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: ${{ env.SNFORGE_VERSION }}

      - name: Install cairo-coverage
        run: curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Run Tests
        run: cd contracts && scarb test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
          flags: contracts
          token: ${{ secrets.CODECOV_TOKEN }}
